# Generated by Django 2.0.3 on 2018-03-22 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview.Topics'),
            preserve_default=False,
        ),
    ]
